apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esync-platform

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml

commonLabels:
  app: esync-platform
  component: api
  version: v1.0.0

images:
  - name: esync-platform
    newTag: v1.0.0

configMapGenerator:
  - name: esync-config
    files:
      - config.yaml