# @GL-governed
# @GL-layer: GL00-09
# @GL-semantic: general-component
# @GL-audit-trail: gl-platform-universe/governance/audit-trails/GL00_09-audit.json
#
# GL Unified Charter Activated
# GL Root Semantic Anchor: gl-platform-universe/governance/GL-ROOT-SEMANTIC-ANCHOR.yaml
# GL Unified Naming Charter: gl-platform-universe/governance/GL-UNIFIED-NAMING-CHARTER.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esync-dev

resources:
  - ../../base/my-app

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment.yaml
  - service.yaml

replicas:
  - name: esync-api-deploy
    count: 1