apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esync-dev

resources:
  - ../../base/my-app

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment.yaml
  - service.yaml

replicas:
  - name: esync-api-deploy
    count: 1