name: iaops-ci

name: IAOPS CI
on:
  push:
    paths:
      - 'iaops/**'
  pull_request:
    paths:
      - 'iaops/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iaops
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.11"
      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -e .[dev]
      - name: lint
        run: |
          python3 -m ruff check src tests
          python3 -m ruff format --check src tests
      - name: test
        run: |
          python3 -m pytest -q
